// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Terradue.OpenNebula {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://opennebula.org/XMLSchema", IsNullable=false)]
    public partial class DATASTORE_POOL {
        
        private DATASTORE[] dATASTOREField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATASTORE")]
        public DATASTORE[] DATASTORE {
            get {
                return this.dATASTOREField;
            }
            set {
                this.dATASTOREField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://opennebula.org/XMLSchema", IsNullable=true)]
    public partial class DATASTORE {
        
        private string iDField;
        
        private string uIDField;
        
        private string gIDField;
        
        private string uNAMEField;
        
        private string gNAMEField;
        
        private string nAMEField;
        
        private DATASTOREPERMISSIONS pERMISSIONSField;
        
        private string dS_MADField;
        
        private string tM_MADField;
        
        private string bASE_PATHField;
        
        private string tYPEField;
        
        private string dISK_TYPEField;
        
        private string cLUSTER_IDField;
        
        private string cLUSTERField;
        
        private string tOTAL_MBField;
        
        private string fREE_MBField;
        
        private string uSED_MBField;
        
        private string[] iMAGESField;
        
        private object tEMPLATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ID {
            get {
                return this.iDField;
            }
            set {
                this.iDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string GID {
            get {
                return this.gIDField;
            }
            set {
                this.gIDField = value;
            }
        }
        
        /// <remarks/>
        public string UNAME {
            get {
                return this.uNAMEField;
            }
            set {
                this.uNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string GNAME {
            get {
                return this.gNAMEField;
            }
            set {
                this.gNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public DATASTOREPERMISSIONS PERMISSIONS {
            get {
                return this.pERMISSIONSField;
            }
            set {
                this.pERMISSIONSField = value;
            }
        }
        
        /// <remarks/>
        public string DS_MAD {
            get {
                return this.dS_MADField;
            }
            set {
                this.dS_MADField = value;
            }
        }
        
        /// <remarks/>
        public string TM_MAD {
            get {
                return this.tM_MADField;
            }
            set {
                this.tM_MADField = value;
            }
        }
        
        /// <remarks/>
        public string BASE_PATH {
            get {
                return this.bASE_PATHField;
            }
            set {
                this.bASE_PATHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string DISK_TYPE {
            get {
                return this.dISK_TYPEField;
            }
            set {
                this.dISK_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CLUSTER_ID {
            get {
                return this.cLUSTER_IDField;
            }
            set {
                this.cLUSTER_IDField = value;
            }
        }
        
        /// <remarks/>
        public string CLUSTER {
            get {
                return this.cLUSTERField;
            }
            set {
                this.cLUSTERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TOTAL_MB {
            get {
                return this.tOTAL_MBField;
            }
            set {
                this.tOTAL_MBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FREE_MB {
            get {
                return this.fREE_MBField;
            }
            set {
                this.fREE_MBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string USED_MB {
            get {
                return this.uSED_MBField;
            }
            set {
                this.uSED_MBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="ID", IsNullable=false)]
        public string[] IMAGES {
            get {
                return this.iMAGESField;
            }
            set {
                this.iMAGESField = value;
            }
        }
        
        /// <remarks/>
        public object TEMPLATE {
            get {
                return this.tEMPLATEField;
            }
            set {
                this.tEMPLATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class DATASTOREPERMISSIONS {
        
        private string oWNER_UField;
        
        private string oWNER_MField;
        
        private string oWNER_AField;
        
        private string gROUP_UField;
        
        private string gROUP_MField;
        
        private string gROUP_AField;
        
        private string oTHER_UField;
        
        private string oTHER_MField;
        
        private string oTHER_AField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string OWNER_U {
            get {
                return this.oWNER_UField;
            }
            set {
                this.oWNER_UField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string OWNER_M {
            get {
                return this.oWNER_MField;
            }
            set {
                this.oWNER_MField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string OWNER_A {
            get {
                return this.oWNER_AField;
            }
            set {
                this.oWNER_AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string GROUP_U {
            get {
                return this.gROUP_UField;
            }
            set {
                this.gROUP_UField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string GROUP_M {
            get {
                return this.gROUP_MField;
            }
            set {
                this.gROUP_MField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string GROUP_A {
            get {
                return this.gROUP_AField;
            }
            set {
                this.gROUP_AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string OTHER_U {
            get {
                return this.oTHER_UField;
            }
            set {
                this.oTHER_UField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string OTHER_M {
            get {
                return this.oTHER_MField;
            }
            set {
                this.oTHER_MField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string OTHER_A {
            get {
                return this.oTHER_AField;
            }
            set {
                this.oTHER_AField = value;
            }
        }
    }
}
