// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Terradue.OpenNebula {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://opennebula.org/XMLSchema", IsNullable=false)]
    public partial class GROUP_POOL {
        
        private object[] itemsField;
        
        private GROUP_POOLDEFAULT_GROUP_QUOTAS dEFAULT_GROUP_QUOTASField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GROUP", Type=typeof(GROUP_POOLGROUP))]
        [System.Xml.Serialization.XmlElementAttribute("QUOTAS", Type=typeof(GROUP_POOLQUOTAS))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public GROUP_POOLDEFAULT_GROUP_QUOTAS DEFAULT_GROUP_QUOTAS {
            get {
                return this.dEFAULT_GROUP_QUOTASField;
            }
            set {
                this.dEFAULT_GROUP_QUOTASField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLGROUP {
        
        private string iDField;
        
        private string nAMEField;
        
        private object tEMPLATEField;
        
        private string[] uSERSField;
        
        private GROUP_POOLGROUPRESOURCE_PROVIDER[] rESOURCE_PROVIDERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ID {
            get {
                return this.iDField;
            }
            set {
                this.iDField = value;
            }
        }
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public object TEMPLATE {
            get {
                return this.tEMPLATEField;
            }
            set {
                this.tEMPLATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="ID", IsNullable=false)]
        public string[] USERS {
            get {
                return this.uSERSField;
            }
            set {
                this.uSERSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESOURCE_PROVIDER")]
        public GROUP_POOLGROUPRESOURCE_PROVIDER[] RESOURCE_PROVIDER {
            get {
                return this.rESOURCE_PROVIDERField;
            }
            set {
                this.rESOURCE_PROVIDERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLQUOTAS {
        
        private string iDField1;
        
        private GROUP_POOLQUOTASDATASTORE_QUOTADATASTORE[] dATASTORE_QUOTAField;
        
        private GROUP_POOLQUOTASNETWORK_QUOTANETWORK[] nETWORK_QUOTAField;
        
        private GROUP_POOLQUOTASVM_QUOTA vM_QUOTAField;
        
        private GROUP_POOLQUOTASIMAGE_QUOTAIMAGE[] iMAGE_QUOTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ID {
            get {
                return this.iDField1;
            }
            set {
                this.iDField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="DATASTORE", IsNullable=false)]
        public GROUP_POOLQUOTASDATASTORE_QUOTADATASTORE[] DATASTORE_QUOTA {
            get {
                return this.dATASTORE_QUOTAField;
            }
            set {
                this.dATASTORE_QUOTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="NETWORK", IsNullable=false)]
        public GROUP_POOLQUOTASNETWORK_QUOTANETWORK[] NETWORK_QUOTA {
            get {
                return this.nETWORK_QUOTAField;
            }
            set {
                this.nETWORK_QUOTAField = value;
            }
        }
        
        /// <remarks/>
        public GROUP_POOLQUOTASVM_QUOTA VM_QUOTA {
            get {
                return this.vM_QUOTAField;
            }
            set {
                this.vM_QUOTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="IMAGE", IsNullable=false)]
        public GROUP_POOLQUOTASIMAGE_QUOTAIMAGE[] IMAGE_QUOTA {
            get {
                return this.iMAGE_QUOTAField;
            }
            set {
                this.iMAGE_QUOTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLQUOTASDATASTORE_QUOTADATASTORE {
        
        private string iDField2;
        
        private string iMAGESField;
        
        private string iMAGES_USEDField;
        
        private string sIZEField;
        
        private string sIZE_USEDField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.iDField2;
            }
            set {
                this.iDField2 = value;
            }
        }
        
        /// <remarks/>
        public string IMAGES {
            get {
                return this.iMAGESField;
            }
            set {
                this.iMAGESField = value;
            }
        }
        
        /// <remarks/>
        public string IMAGES_USED {
            get {
                return this.iMAGES_USEDField;
            }
            set {
                this.iMAGES_USEDField = value;
            }
        }
        
        /// <remarks/>
        public string SIZE {
            get {
                return this.sIZEField;
            }
            set {
                this.sIZEField = value;
            }
        }
        
        /// <remarks/>
        public string SIZE_USED {
            get {
                return this.sIZE_USEDField;
            }
            set {
                this.sIZE_USEDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLQUOTASNETWORK_QUOTANETWORK {
        
        private string iDField3;
        
        private string lEASESField;
        
        private string lEASES_USEDField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.iDField3;
            }
            set {
                this.iDField3 = value;
            }
        }
        
        /// <remarks/>
        public string LEASES {
            get {
                return this.lEASESField;
            }
            set {
                this.lEASESField = value;
            }
        }
        
        /// <remarks/>
        public string LEASES_USED {
            get {
                return this.lEASES_USEDField;
            }
            set {
                this.lEASES_USEDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLQUOTASVM_QUOTA {
        
        private GROUP_POOLQUOTASVM_QUOTAVM vMField;
        
        /// <remarks/>
        public GROUP_POOLQUOTASVM_QUOTAVM VM {
            get {
                return this.vMField;
            }
            set {
                this.vMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLQUOTASVM_QUOTAVM {
        
        private string cPUField;
        
        private string cPU_USEDField;
        
        private string mEMORYField;
        
        private string mEMORY_USEDField;
        
        private string vMSField;
        
        private string vMS_USEDField;
        
        private string vOLATILE_SIZEField;
        
        private string vOLATILE_SIZE_USEDField;
        
        /// <remarks/>
        public string CPU {
            get {
                return this.cPUField;
            }
            set {
                this.cPUField = value;
            }
        }
        
        /// <remarks/>
        public string CPU_USED {
            get {
                return this.cPU_USEDField;
            }
            set {
                this.cPU_USEDField = value;
            }
        }
        
        /// <remarks/>
        public string MEMORY {
            get {
                return this.mEMORYField;
            }
            set {
                this.mEMORYField = value;
            }
        }
        
        /// <remarks/>
        public string MEMORY_USED {
            get {
                return this.mEMORY_USEDField;
            }
            set {
                this.mEMORY_USEDField = value;
            }
        }
        
        /// <remarks/>
        public string VMS {
            get {
                return this.vMSField;
            }
            set {
                this.vMSField = value;
            }
        }
        
        /// <remarks/>
        public string VMS_USED {
            get {
                return this.vMS_USEDField;
            }
            set {
                this.vMS_USEDField = value;
            }
        }
        
        /// <remarks/>
        public string VOLATILE_SIZE {
            get {
                return this.vOLATILE_SIZEField;
            }
            set {
                this.vOLATILE_SIZEField = value;
            }
        }
        
        /// <remarks/>
        public string VOLATILE_SIZE_USED {
            get {
                return this.vOLATILE_SIZE_USEDField;
            }
            set {
                this.vOLATILE_SIZE_USEDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLQUOTASIMAGE_QUOTAIMAGE {
        
        private string iDField4;
        
        private string rVMSField;
        
        private string rVMS_USEDField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.iDField4;
            }
            set {
                this.iDField4 = value;
            }
        }
        
        /// <remarks/>
        public string RVMS {
            get {
                return this.rVMSField;
            }
            set {
                this.rVMSField = value;
            }
        }
        
        /// <remarks/>
        public string RVMS_USED {
            get {
                return this.rVMS_USEDField;
            }
            set {
                this.rVMS_USEDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLGROUPRESOURCE_PROVIDER {
        
        private string zONE_IDField;
        
        private string cLUSTER_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ZONE_ID {
            get {
                return this.zONE_IDField;
            }
            set {
                this.zONE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CLUSTER_ID {
            get {
                return this.cLUSTER_IDField;
            }
            set {
                this.cLUSTER_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLDEFAULT_GROUP_QUOTAS {
        
        private GROUP_POOLDEFAULT_GROUP_QUOTASDATASTORE_QUOTADATASTORE[] dATASTORE_QUOTAField1;
        
        private GROUP_POOLDEFAULT_GROUP_QUOTASNETWORK_QUOTANETWORK[] nETWORK_QUOTAField1;
        
        private GROUP_POOLDEFAULT_GROUP_QUOTASVM_QUOTA vM_QUOTAField1;
        
        private GROUP_POOLDEFAULT_GROUP_QUOTASIMAGE_QUOTAIMAGE[] iMAGE_QUOTAField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="DATASTORE", IsNullable=false)]
        public GROUP_POOLDEFAULT_GROUP_QUOTASDATASTORE_QUOTADATASTORE[] DATASTORE_QUOTA {
            get {
                return this.dATASTORE_QUOTAField1;
            }
            set {
                this.dATASTORE_QUOTAField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="NETWORK", IsNullable=false)]
        public GROUP_POOLDEFAULT_GROUP_QUOTASNETWORK_QUOTANETWORK[] NETWORK_QUOTA {
            get {
                return this.nETWORK_QUOTAField1;
            }
            set {
                this.nETWORK_QUOTAField1 = value;
            }
        }
        
        /// <remarks/>
        public GROUP_POOLDEFAULT_GROUP_QUOTASVM_QUOTA VM_QUOTA {
            get {
                return this.vM_QUOTAField1;
            }
            set {
                this.vM_QUOTAField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="IMAGE", IsNullable=false)]
        public GROUP_POOLDEFAULT_GROUP_QUOTASIMAGE_QUOTAIMAGE[] IMAGE_QUOTA {
            get {
                return this.iMAGE_QUOTAField1;
            }
            set {
                this.iMAGE_QUOTAField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLDEFAULT_GROUP_QUOTASDATASTORE_QUOTADATASTORE {
        
        private string iDField5;
        
        private string iMAGESField1;
        
        private string iMAGES_USEDField1;
        
        private string sIZEField1;
        
        private string sIZE_USEDField1;
        
        /// <remarks/>
        public string ID {
            get {
                return this.iDField5;
            }
            set {
                this.iDField5 = value;
            }
        }
        
        /// <remarks/>
        public string IMAGES {
            get {
                return this.iMAGESField1;
            }
            set {
                this.iMAGESField1 = value;
            }
        }
        
        /// <remarks/>
        public string IMAGES_USED {
            get {
                return this.iMAGES_USEDField1;
            }
            set {
                this.iMAGES_USEDField1 = value;
            }
        }
        
        /// <remarks/>
        public string SIZE {
            get {
                return this.sIZEField1;
            }
            set {
                this.sIZEField1 = value;
            }
        }
        
        /// <remarks/>
        public string SIZE_USED {
            get {
                return this.sIZE_USEDField1;
            }
            set {
                this.sIZE_USEDField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLDEFAULT_GROUP_QUOTASNETWORK_QUOTANETWORK {
        
        private string iDField6;
        
        private string lEASESField1;
        
        private string lEASES_USEDField1;
        
        /// <remarks/>
        public string ID {
            get {
                return this.iDField6;
            }
            set {
                this.iDField6 = value;
            }
        }
        
        /// <remarks/>
        public string LEASES {
            get {
                return this.lEASESField1;
            }
            set {
                this.lEASESField1 = value;
            }
        }
        
        /// <remarks/>
        public string LEASES_USED {
            get {
                return this.lEASES_USEDField1;
            }
            set {
                this.lEASES_USEDField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLDEFAULT_GROUP_QUOTASVM_QUOTA {
        
        private GROUP_POOLDEFAULT_GROUP_QUOTASVM_QUOTAVM vMField1;
        
        /// <remarks/>
        public GROUP_POOLDEFAULT_GROUP_QUOTASVM_QUOTAVM VM {
            get {
                return this.vMField1;
            }
            set {
                this.vMField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLDEFAULT_GROUP_QUOTASVM_QUOTAVM {
        
        private string cPUField1;
        
        private string cPU_USEDField1;
        
        private string mEMORYField1;
        
        private string mEMORY_USEDField1;
        
        private string vMSField1;
        
        private string vMS_USEDField1;
        
        /// <remarks/>
        public string CPU {
            get {
                return this.cPUField1;
            }
            set {
                this.cPUField1 = value;
            }
        }
        
        /// <remarks/>
        public string CPU_USED {
            get {
                return this.cPU_USEDField1;
            }
            set {
                this.cPU_USEDField1 = value;
            }
        }
        
        /// <remarks/>
        public string MEMORY {
            get {
                return this.mEMORYField1;
            }
            set {
                this.mEMORYField1 = value;
            }
        }
        
        /// <remarks/>
        public string MEMORY_USED {
            get {
                return this.mEMORY_USEDField1;
            }
            set {
                this.mEMORY_USEDField1 = value;
            }
        }
        
        /// <remarks/>
        public string VMS {
            get {
                return this.vMSField1;
            }
            set {
                this.vMSField1 = value;
            }
        }
        
        /// <remarks/>
        public string VMS_USED {
            get {
                return this.vMS_USEDField1;
            }
            set {
                this.vMS_USEDField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class GROUP_POOLDEFAULT_GROUP_QUOTASIMAGE_QUOTAIMAGE {
        
        private string iDField7;
        
        private string rVMSField1;
        
        private string rVMS_USEDField1;
        
        /// <remarks/>
        public string ID {
            get {
                return this.iDField7;
            }
            set {
                this.iDField7 = value;
            }
        }
        
        /// <remarks/>
        public string RVMS {
            get {
                return this.rVMSField1;
            }
            set {
                this.rVMSField1 = value;
            }
        }
        
        /// <remarks/>
        public string RVMS_USED {
            get {
                return this.rVMS_USEDField1;
            }
            set {
                this.rVMS_USEDField1 = value;
            }
        }
    }
}
