// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Terradue.OpenNebula {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://opennebula.org/XMLSchema", IsNullable=false)]
    public partial class HOST_POOL {
        
        private HOST[] hOSTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HOST")]
        public HOST[] HOST {
            get {
                return this.hOSTField;
            }
            set {
                this.hOSTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://opennebula.org/XMLSchema", IsNullable=true)]
    public partial class HOST {
        
        private string iDField;
        
        private string nAMEField;
        
        private string sTATEField;
        
        private string iM_MADField;
        
        private string vM_MADField;
        
        private string vN_MADField;
        
        private string lAST_MON_TIMEField;
        
        private string cLUSTER_IDField;
        
        private string cLUSTERField;
        
        private HOSTHOST_SHARE hOST_SHAREField;
        
        private string[] vMSField;
        
        private object tEMPLATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ID {
            get {
                return this.iDField;
            }
            set {
                this.iDField = value;
            }
        }
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        public string IM_MAD {
            get {
                return this.iM_MADField;
            }
            set {
                this.iM_MADField = value;
            }
        }
        
        /// <remarks/>
        public string VM_MAD {
            get {
                return this.vM_MADField;
            }
            set {
                this.vM_MADField = value;
            }
        }
        
        /// <remarks/>
        public string VN_MAD {
            get {
                return this.vN_MADField;
            }
            set {
                this.vN_MADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string LAST_MON_TIME {
            get {
                return this.lAST_MON_TIMEField;
            }
            set {
                this.lAST_MON_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CLUSTER_ID {
            get {
                return this.cLUSTER_IDField;
            }
            set {
                this.cLUSTER_IDField = value;
            }
        }
        
        /// <remarks/>
        public string CLUSTER {
            get {
                return this.cLUSTERField;
            }
            set {
                this.cLUSTERField = value;
            }
        }
        
        /// <remarks/>
        public HOSTHOST_SHARE HOST_SHARE {
            get {
                return this.hOST_SHAREField;
            }
            set {
                this.hOST_SHAREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="ID", IsNullable=false)]
        public string[] VMS {
            get {
                return this.vMSField;
            }
            set {
                this.vMSField = value;
            }
        }
        
        /// <remarks/>
        public object TEMPLATE {
            get {
                return this.tEMPLATEField;
            }
            set {
                this.tEMPLATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class HOSTHOST_SHARE {
        
        private string dISK_USAGEField;
        
        private string mEM_USAGEField;
        
        private string cPU_USAGEField;
        
        private string mAX_DISKField;
        
        private string mAX_MEMField;
        
        private string mAX_CPUField;
        
        private string fREE_DISKField;
        
        private string fREE_MEMField;
        
        private string fREE_CPUField;
        
        private string uSED_DISKField;
        
        private string uSED_MEMField;
        
        private string uSED_CPUField;
        
        private string rUNNING_VMSField;
        
        private HOSTHOST_SHAREDATASTORESDS[] dATASTORESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string DISK_USAGE {
            get {
                return this.dISK_USAGEField;
            }
            set {
                this.dISK_USAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MEM_USAGE {
            get {
                return this.mEM_USAGEField;
            }
            set {
                this.mEM_USAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CPU_USAGE {
            get {
                return this.cPU_USAGEField;
            }
            set {
                this.cPU_USAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MAX_DISK {
            get {
                return this.mAX_DISKField;
            }
            set {
                this.mAX_DISKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MAX_MEM {
            get {
                return this.mAX_MEMField;
            }
            set {
                this.mAX_MEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MAX_CPU {
            get {
                return this.mAX_CPUField;
            }
            set {
                this.mAX_CPUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FREE_DISK {
            get {
                return this.fREE_DISKField;
            }
            set {
                this.fREE_DISKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FREE_MEM {
            get {
                return this.fREE_MEMField;
            }
            set {
                this.fREE_MEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FREE_CPU {
            get {
                return this.fREE_CPUField;
            }
            set {
                this.fREE_CPUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string USED_DISK {
            get {
                return this.uSED_DISKField;
            }
            set {
                this.uSED_DISKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string USED_MEM {
            get {
                return this.uSED_MEMField;
            }
            set {
                this.uSED_MEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string USED_CPU {
            get {
                return this.uSED_CPUField;
            }
            set {
                this.uSED_CPUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string RUNNING_VMS {
            get {
                return this.rUNNING_VMSField;
            }
            set {
                this.rUNNING_VMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="DS", IsNullable=false)]
        public HOSTHOST_SHAREDATASTORESDS[] DATASTORES {
            get {
                return this.dATASTORESField;
            }
            set {
                this.dATASTORESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opennebula.org/XMLSchema")]
    public partial class HOSTHOST_SHAREDATASTORESDS {
        
        private string iDField1;
        
        private string fREE_MBField;
        
        private string tOTAL_MBField;
        
        private string uSED_MBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ID {
            get {
                return this.iDField1;
            }
            set {
                this.iDField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FREE_MB {
            get {
                return this.fREE_MBField;
            }
            set {
                this.fREE_MBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TOTAL_MB {
            get {
                return this.tOTAL_MBField;
            }
            set {
                this.tOTAL_MBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string USED_MB {
            get {
                return this.uSED_MBField;
            }
            set {
                this.uSED_MBField = value;
            }
        }
    }
}
